import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

import HeaderDes from "../components/header/HeaderDes";

import HeaderMob from "@/components/header/HeaderMob";
import NavigationBar from "@/components/main/components/navigationBar/NavigationBar";

const vazirFont = localFont({
  src: "../font/Vazirmatn-Regular.ttf",
});

export const metadata: Metadata = {
  title: "ebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.className} antialiased`}>
        <HeaderDes />
        <HeaderMob />
        <div className="w-full min-h-screen bg-[#F5F6F8]">{children}</div>
        <NavigationBar />
      </body>
    </html>
  );
}
