import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const vazirFont = localFont({
  src: "../font/Vazirmatn-Regular.ttf",
});

export const metadata: Metadata = {
  title: "ebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={`${vazirFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
